#### numpy 모듈의 호출

In [1]:
import numpy as np

#### array의 생성

In [3]:
a = [1, 2, 3, 4, 5]
b = [5, 4, 3, 2, 1]

In [5]:
a = np.array(a, int)
a

array([1, 2, 3, 4, 5])

In [6]:
test_array = np.array(["1", "4", 5, 8], float)
test_array

array([1., 4., 5., 8.])

In [7]:
type(test_array[3])

numpy.float64

In [8]:
test_array = np.array([1, 4, 5, "8"], float)  # String Type의 데이터를 입력해도
test_array

array([1., 4., 5., 8.])

In [10]:
type(test_array[3])  # Float Type으로 자동 형변환을 실시

numpy.float64

In [14]:
a = [1, 2, 3, 4, 5]
b = [5, 4, 3, 2, 1]
a[0] is b[-1]

True

In [18]:
a = np.array(a)
b = np.array(b)
a[0] is b[-1]

False

In [20]:
test_array.dtype  # Array(배열) 전체의 데이터 Type을 반환함

dtype('float64')

In [31]:
a = [[1, 2, 3], [4, 5, 6], [4, 5, 6]]

In [32]:
np.array(a).shape

(3, 3)

#### arrary shape

In [34]:
vector = [1, 2, 3, 4]
np.array(vector, int).shape

(4,)

In [36]:
matrix = [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]]
np.array(matrix, int)

array([[1, 2, 5, 8],
       [1, 2, 5, 8],
       [1, 2, 5, 8]])

In [38]:
tensor = [
    [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]],
    [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]],
    [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]],
    [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]],
]
np.array(tensor, int).shape

(4, 3, 4)

In [41]:
np.array(tensor, int).ndim

3

In [46]:
np.array(tensor, int).size

48

#### numpy dtype

In [53]:
a = np.array([[1, 2, 3], [4.5, 5, 6]], dtype=np.int8)

In [54]:
a.dtype

dtype('int8')

In [56]:
np.array([[1, 2, 3], [4.5, "5", "6"]], dtype=np.float32).nbytes

24

In [ ]:
np.array([[1, 2, 3], [4.5, "5", "6"]], dtype=np.float32).nbytes

In [ ]:
np.array([[1, 2, 3], [4.5, "5", "6"]], dtype=np.int8).nbytes

In [ ]:
np.array([[1, 2, 3], [4.5, "5", "6"]], dtype=np.float64).nbytes