In [1]:
import numpy as np

In [2]:
test_exmaple = np.array([[1, 2, 3], [4.5, 5, 6]], int)
test_exmaple

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
test_exmaple[0][2]

3

In [4]:
test_exmaple[0, 2]

3

In [5]:
test_exmaple[0, 0] = 10  # Matrix 0,0 에 12 할당
test_exmaple

array([[10,  2,  3],
       [ 4,  5,  6]])

In [6]:
test_exmaple[1, 2] = 5  # Matrix 0,0 에 12 할당
test_exmaple[1, 2]

5

In [7]:
test_exmaple

array([[10,  2,  3],
       [ 4,  5,  5]])

#### slicing

In [8]:
test_exmaple = np.array([[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]], int)
test_exmaple

array([[1, 2, 5, 8],
       [1, 2, 5, 8],
       [1, 2, 5, 8],
       [1, 2, 5, 8]])

In [9]:
test_exmaple[:, 2:]

array([[5, 8],
       [5, 8],
       [5, 8],
       [5, 8]])

In [10]:
test_exmaple

array([[1, 2, 5, 8],
       [1, 2, 5, 8],
       [1, 2, 5, 8],
       [1, 2, 5, 8]])

In [11]:
test_exmaple[:, 1:3].shape

(4, 2)

In [12]:
test_exmaple

array([[1, 2, 5, 8],
       [1, 2, 5, 8],
       [1, 2, 5, 8],
       [1, 2, 5, 8]])

In [13]:
test_exmaple[1:2, :2]

array([[1, 2]])

In [14]:
test_exmaple = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]], int)
test_exmaple

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [15]:
test_exmaple[1]  # 1 Row의 1열 ~ 2열

array([ 6,  7,  8,  9, 10])

In [16]:
test_exmaple[1:3]  # 1 Row ~ 2Row의 전체

array([[ 6,  7,  8,  9, 10]])

In [17]:
a = np.arange(100).reshape(10, 10)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [18]:
a[:, -1]

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])