In [1]:
import numpy as np

#### all & any

In [2]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
a < 4

array([ True,  True,  True,  True, False, False, False, False, False,
       False])

In [8]:
a < 1

array([ True, False, False, False, False, False, False, False, False,
       False])

In [12]:
np.all(a < 10)

True

In [13]:
np.any(a > 5), np.any(a < 0)

(True, False)

In [14]:
np.all(a > 5), np.all(a < 10)

(False, True)

#### comparision operation

In [15]:
test_a = np.array([1, 3, 0], float)
test_b = np.array([5, 2, 1], float)

In [16]:
test_a > test_b

array([False,  True, False])

In [18]:
test_a >= test_b

array([False,  True, False])

In [20]:
(test_a > test_b).any()

True

In [ ]:
a = np.array([1, 3, 0], float)
a > 0

In [22]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
np.logical_and(a > 0, a < 3)  # and 조건의 condition

array([False,  True,  True, False, False, False, False, False, False,
       False])

In [24]:
b = np.array([True, False, True], bool)
np.logical_not(b)

array([False,  True, False])

In [27]:
c = np.array([False, True, False], bool)
c

array([False,  True, False])

In [28]:
np.logical_or(b, c)  # OR 조건의 condition

array([ True,  True,  True])

## np.where

In [34]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
np.where(a > 5)

(array([6, 7, 8, 9], dtype=int64),)

In [37]:
np.where(a > 5, 3, 2)  # where(condition, TRUE, FALSE)

array([2, 2, 2, 2, 2, 2, 3, 3, 3, 3])

In [ ]:
a = np.arange(5, 15)
a

In [ ]:
np.where(a > 10)

In [40]:
a = np.array([1, np.NaN, np.Inf], float)
np.isnan(a)

array([False,  True, False])

In [41]:
np.isfinite(a)

array([ True, False, False])

#### argmax & argmin

In [42]:
a = np.array([1, 2, 4, 5, 8, 78, 23, 3])
a

array([ 1,  2,  4,  5,  8, 78, 23,  3])

In [44]:
a.argsort()[::-1]

array([5, 6, 4, 3, 2, 7, 1, 0], dtype=int64)

In [45]:
np.argmax(a), np.argmin(a)

(5, 0)

In [46]:
a = np.array([[1, 2, 4, 7], [9, 88, 6, 45], [9, 76, 3, 4]])
a

array([[ 1,  2,  4,  7],
       [ 9, 88,  6, 45],
       [ 9, 76,  3,  4]])

In [47]:
np.argmax(a, axis=1), np.argmin(a, axis=0)

(array([3, 1, 1], dtype=int64), array([0, 0, 2, 2], dtype=int64))